version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Build started on `date`
      - mvn install
  build:
    commands:
      - echo Build in progress...
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/restart_server.sh
  discard-paths: yes